name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: HACS validation
        uses: "hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa" # main
        with:
          category: "integration"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@868e6cb4607727d764341a158d98872cd63fa658" # master
